cobu/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'
# from users import views

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('new-post/', views.post_new, name="new-post"),
    path('<slug:slug>', views.post_page, name="page"),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
# from users import views

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


PLAYSTYLE_CHOICES = (
    ('relaxed', 'RELAXED'),
    ('regular', 'REGULAR'),
    ('competitive', 'COMPETITIVE')
)

PLATFORM_CHOICES = (
    ('playstation', 'PLAYSTATION'),
    ('xbox', 'XBOX'),
    ('nintendo', 'NINTENDO'),
    ('pc', 'PC')
)

STATUS = ((0, "Draft"), (1, "Published"))

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75, unique=True)
    body = models.TextField()
    platform = models.CharField(max_length=11, choices=PLATFORM_CHOICES, default='pc')
    playstyle = models.CharField(max_length=11, choices=PLAYSTYLE_CHOICES, default='relaxed')
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    date = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from . import models
from .models import Comment

class CreatePost(forms.ModelForm):   
    class Meta:
        model = models.Post
        fields = ('title','body','platform','playstyle','slug')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        fields = ('name', 'body')

cobu/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse("Hello World! Can you see me?")
    return render(request, 'home.html')

def about(request):
    # return HttpResponse("This is my about page!")
    return render(request, 'about.html')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms
from .forms import CommentForm

# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts': posts})


def post_page(request, slug):
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect('post_page', slug=post.slug)
    else:
        comment_form = CommentForm()
    return render(request, 'posts/post_page.html', {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form})


@login_required(login_url="/users/login/")
def post_new(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', {'form': form})
    

signup/views.py
# from django.shortcuts import render

# # Create your views here.
# def signup(response):
#     return render()

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# # Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, "users/register.html", {"form":form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:list")
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", {"form":form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:list")
    

posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title %}
    New Post
{% endblock %}

{% block content %}
    <section>
        <h1>New Post</h1> 
        <form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Add Post</button>
        </form>
    </section>                 
{% endblock %}

posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <section>
    <h1>{{ post.title }}</h1>          
        <p>{{ post.date }}</p>
        <p>{{ post.body }}</p>
        <p>{{ post.platform }} || {{ post.playstyle }}</p>  
        
        <h3>Comments</h3>
        {% for comment in comments %}
            <div>
                <p><strong>{{ comment.name }}</strong> - {{ comment.created_on }}</p>
                <p>{{ comment.body }}</p>
            </div>
        {% empty %}
            <p>No comments yet.</p>
        {% endfor %}

        <h3>Leave a comment</h3>
        {% if new_comment %}
            <p>Your comment has been added.</p>
        {% else %}
            <form method="post">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <button type="submit">Add comment</button>
            </form>
        {% endif %}
    </section>
{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Mission Board
{% endblock %}

{% block content %}
    <section>
    <h1>Mission Board</h1>

    {% for post in posts %}
        <article class="post">
            <h2>
                <a href="{% url 'posts:page' slug=post.slug %}">
                {{ post.title }}
            </h2>
            <p>{{ post.date }} by {{ post.author }}</p>
            <p>{{ post.body }}</p>
            <p>{{ post.platform }} || {{ post.playstyle }}</p>
        </article>
    {% endfor %}
    </section>



{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page.</p>
</body>
</html>

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>Check out my <a href="/about">About</a> page.</p>
{% endblock %}

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django-Setup</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" >
</head>
<body>
    <h1>If you're seeing this in RED, static files are being served</h1>
    
</body>
</html>

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/">
            <span aria-label="Home" title="Home">Home</span></a> |
        <a href="{% url 'posts:list' %}">
            <span aria-label="Posts" title="Posts">Posts</span></a> |
        <a href="/about">
            <span aria-label="About" title="About">About</span></a> |
        {% if user.is_authenticated %}
            <a href="{% url 'posts:new-post' %}">
                <span aria-label="New Post" title="New Post">New Post</span></a>
            <form class="logout" action="{% url 'users:logout' %}" method="post">
            {% csrf_token %}
            <button class="logout-button" aria-label="User Logout" title="User Logout">Logout</button>
        </form> 
        {% else %}  
            <a href="{% url 'users:register' %}">
                <span aria-label="Sign-up" title="Sign-up">Sign Up</span></a> |
            <a href="{% url 'users:login' %}">
                <span aria-label="User Login" title="User Login">Login</span></a>
        {% endif %}
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    User Login
{% endblock %}

{% block content %}
    <section>
    <h1>User Login</h1>
    <form class="signup" action="/users/login/" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" /> 
        {% endif %}
        <button class="signup-submit">Submit</button>
    </form>
{% endblock %}

users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    A Squad Needs YOU! Sign Up Now!
{% endblock %}

{% block content %}
    <section>
    <h1>A Squad Needs YOU! Sign Up Now!</h1>          
{% endblock %}